Refine space around the inner sides of parenthesis `(` and `)`
- Ensure that `(` is followed by a space if and only if the balancing `)` follows a space
     Exception: In the strings,
                   when the nearest character at the one of the inner sides is a Han character
                      and the nearest non-space character at the other inner side is not,
                   there can be a space at the non-Han-character inner side.

(cherry picked from commit 82a649bcae1d9513bf8b3b0aa6936376ae7802ca)