Ensure there is exactly a single space after `if`/`switch`/`for`/`while` keywords
Exception: Using 6 spaces after `if` is allowed
              to align the condition list of `if` and `else if`.
(cherry picked from commit 3ff10d018923394ed3b3ffa651a075271c8eb8b8)